PubFunction = /Users/wuyuhang/Desktop/C_Project/Recite_EnglishTense/Public_Function/MyStdlib.c
RandWord = /Users/wuyuhang/Desktop/C_Project/Recite_EnglishTense/RandWordMode/RandWordFunction.c
ReciteWord = /Users/wuyuhang/Desktop/C_Project/Recite_EnglishTense/ReciteWordMode/ReciteFunction.c

all:
	gcc $(PubFunction) $(RandWord) $(ReciteWord) main.c -o ReciteWord

open:
	./ReciteWord